### PR TITLE
[Lib] Fix memory allocation for DNS query

### PR DESCRIPTION
**Pull request by KernelErr**
Signed-off-by: KernelErr <me@lirui.tech>

Please yank the previous two versions in order to prevent potential bugs. @hydai

### CODE REVIEW

**Comment by KernelErr** [comment]
If relocation of vector happened, there would be problems for reading parameter pointers. I will check if it's WasmEdge's bug or other.

**Comment by hydai** [comment]
> If relocation of vector happened, there would be problems for reading parameter pointers. I will check if it's WasmEdge's bug or other.

Not sure if this is related or not. Please notice that WasmEdge had process the return values of `getaddrinfo` from linked list to a vector: https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/inode-linux.cpp#L802-L841

**Comment by KernelErr** [comment]
Seems that it's because of the reallocation of the vector when dynamically pushing elements. When a vector reached its capacity, the elements' addresses would be changed. However, the old invalid address may still be kept.

The solution is every vector transmitted from Rust to C++, we should ensure all memory address is correct. Use `resize` and `with_capacity` instead of dynamically operations.

**Comment by KernelErr** [comment]
I have seen there is a PR for handling '\0' in WasmEdge. Should we also add it to other host functions like `WasiPathCreateDirectory`?

**Comment by hydai** [comment]
> I have seen there is a PR for handling '\0' in WasmEdge. Should we also add it to other host functions like `WasiPathCreateDirectory`?

It's handled. https://github.com/WasmEdge/WasmEdge/blob/66a9cc2e60168866861cdf6f4dd2fd1c2303ca7d/include/host/wasi/environ.h#L597

We convert the ptr + length to string_view. So it's fine.

**Comment by KernelErr** [comment]
I think bugs are fixed.

`wasiaddrinfo_array` linked list from Rust side to WasmEdge:
image

`AiAddrSaDataArray` memory address and its length:
image

**Review by hydai — APPROVED** [review]

**Pull request merged**
