### PR TITLE
Update dependent version of bytes

### PR DESCRIPTION
**Pull request by DarumaDocker**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by juntao — APPROVED** [review]

**Comment by juntao** [comment]
Shall we publish it to crates.io?

**Review by L-jasmine — APPROVED** [review]

**Comment by L-jasmine** [comment]
> Shall we publish it to crates.io?

yes

**Comment by DarumaDocker** [comment]
@juntao We don't have authority to merge.

**Pull request merged**
